const DEFAULT_PERMISSIONS = [
  { key: "manage_users", label: "Manage Users" },
  { key: "manage_subscriptions", label: "Manage Subscriptions" },
  { key: "upload_content", label: "Upload Content" },
  { key: "edit_content", label: "Edit Content" },
  { key: "publish_podcast", label: "Publish Podcast" },
  { key: "send_notifications", label: "Send Notifications" },
  { key: "view_analytics", label: "View Analytics" },
  { key: "manage_roles", label: "Manage Roles" },
  { key: "billing_access", label: "Billing Access" },
  { key: "access_settings", label: "Access Settings" },
];

const DEFAULT_ROLES = {
  admin: {
    key: "admin",
    label: "Admin",
    users: 1,
    permissions: {
      manage_users: true,
      manage_subscriptions: true,
      upload_content: true,
      edit_content: true,
      publish_podcast: true,
      send_notifications: true,
      view_analytics: true,
      manage_roles: true,
      billing_access: true,
      access_settings: true,
    },
  },
  coach: {
    key: "coach",
    label: "Coach",
    users: 0,
    permissions: {
      manage_users: false,
      manage_subscriptions: false,
      upload_content: true,
      edit_content: true,
      publish_podcast: true,
      send_notifications: false,
      view_analytics: true,
      manage_roles: false,
      billing_access: false,
      access_settings: false,
    },
  },
  moderator: {
    key: "moderator",
    label: "Moderator",
    users: 0,
    permissions: {
      manage_users: true,
      manage_subscriptions: false,
      upload_content: false,
      edit_content: true,
      publish_podcast: false,
      send_notifications: true,
      view_analytics: true,
      manage_roles: false,
      billing_access: false,
      access_settings: false,
    },
  },
  member: {
    key: "member",
    label: "Member",
    users: 0,
    permissions: {
      manage_users: false,
      manage_subscriptions: false,
      upload_content: false,
      edit_content: false,
      publish_podcast: false,
      send_notifications: false,
      view_analytics: false,
      manage_roles: false,
      billing_access: false,
      access_settings: false,
    },
  },
};

module.exports = { DEFAULT_PERMISSIONS, DEFAULT_ROLES };
